### ISSUE TITLE
Error on creating output file

### ISSUE THREAD

**Issue by oliroe** [RhinoRhys/radarr-collections#102]
Hi

I've just upgraded to the latest version and receiving the following error message when running as '-c'
![image](https://user-images.githubusercontent.com/4500141/54183516-4386b780-449c-11e9-8754-950febd663a2.png)

This is the error when doing a full scan '-f'
![image](https://user-images.githubusercontent.com/4500141/54183580-6d3fde80-449c-11e9-938b-9eec8cb05571.png)

**Comment by oliroe** [comment]
I've done my setup from scratch using the latest version and it runs fine, looks like it was something in the upgrade that broke my setup. OK to close

**Comment by RhinoRhys** [comment]
Yeah sorry that was me changing something in `words.conf`, glad everything is running fine now.

Having `.default` in the config file names allows you overwrite everything in the folder safely without changing your edited `rcm.conf` file. Ideally you want to replace every file when you upgrade, not just `rcm.py`. I've also added in update warnings for the config files now as I keep changing stuff haha. It should all be good now though, I'll stop :)
