### ISSUE TITLE
Issue on Mac

### ISSUE THREAD

**Issue by CancelIFR** [RhinoRhys/radarr-collections#103]
Getting this when I run it on Mac

`Traceback (most recent call last):
  File "rcm.py", line 304, in <module>
    config_path = get_dir(sys.argv[1])
IndexError: list index out of range`

**Comment by RhinoRhys** [comment]
You need to run it as `python rcm.py ./config` if the config folder is in the same directory as the rcm.py script. I've updated to print a help text in future.
