### ISSUE TITLE
Error - Profile template for People monitoring not recognised as a number - Exiting

### ISSUE THREAD

**Issue by scr44tch** [RhinoRhys/radarr-collections#107]
Hi,

first of all thank you very much, i was looking for something like this for a time now.

i have a problem while searching for people:
here is my people.conf

[Quentin Tarantino]
id = 138
monitor = Directing, Production, Writing
reject =
min_year = 0

when i run the script with the people option
python rcm.py ./config -p

i get this error:

Error - Profile template for People monitoring not recognised as a number - Exiting

im running this on Ubuntu 18.04.4

**Comment by RhinoRhys** [comment]
In the otherqq config file there is the "profile" parameter. You need to choose an existing movie in your Radarr library, get the TMDB ID for it and place that ID there. The script needs a template to copy certain information from to be able to add new movies to the database.
