### ISSUE TITLE
NameError: name 'old_unmon' is not defined

### ISSUE THREAD

**Issue by traubm** [RhinoRhys/radarr-collections#109]
During an initial scan got:

Traceback (most recent call last):
  File "D:\src\RadarrCollectionandPeopleManager\rcm.py", line 507, in <module>
    if movie["tmdbId"] not in old_unmon + old_want: log(words[u'text'][u'unmonitored'].format(logtext))
NameError: name 'old_unmon' is not defined
Found 0 Movies

Remedied by adding:
    old_want, old_unmon = [],[]
after #397
    skip, col_ids = [],[]

**Comment by damousys** [comment]
Thanks, fixed it for me.
Can you create a PR for it ?

**Comment by damousys** [comment]
Created a PR
https://github.com/RhinoRhys/radarr-collections/pull/112
