### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not list

### ISSUE THREAD

**Issue by joshhazel** [RhinoRhys/radarr-collections#119]
Running this app for the very first time -
Windows 10 v19043.1165 x64
Radarr Version3.2.2.5080
Python v3.9.7
radarr-collections pulled from master today Sept 5 2021

Received following error when it was trying to add 100 Women

```
[21-09-05 09:11:39] >>                     TMDB ID: 20648     100 Women (2002)                                                                                                 Adding to Wanted
Traceback (most recent call last):
  File "c:\radarr-collections-master\rcm.py", line 522, in <module>
    else: tmdb_check(movie["tmdbId"])
  File "c:\radarr-collections-master\rcm.py", line 288, in tmdb_check
    collection_check(col_id, tmdbId)
  File "c:\radarr-collections-master\rcm.py", line 276, in collection_check
    for id_check in parts:  database_check(id_check, white_name, col_json, input_id)
  File "c:\radarr-collections-master\rcm.py", line 202, in database_check
    path = os.path.join([rootpath, folder])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not list
Found 0 Movies
```

**Comment by paulkoorn** [comment]
i have the same error on the same movie

**Comment by hjosephhurley** [comment]
I'm also getting this error on multiple movies.  If I add an offending movie to the blacklist, the script proceeds.  I walked through about 30 and it seems the script throws this error for me anytime it comes across a movie not already in Radarr at the step "Adding to Wanted".  Movies in Radarr process fine, but if the script finds a movie not yet in the DB, it throws this error.  

I'm on Ubuntu 20.10 using Python 3.8.10.

`Adding to Wanted
Traceback (most recent call last):
  File "rcm.py", line 546, in <module>
    person_check(person)
  File "rcm.py", line 325, in person_check
    database_check(movie['id'], white_name, per_json, " - Cast - " + movie[u'character'].title())
  File "rcm.py", line 202, in database_check
    path = os.path.join([rootpath, folder])
  File "/usr/lib/python3.8/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not list`

**Comment by joshhazel** [comment]
> Okay guys... so I claim to know nothing about Python... but understanding it was a data typing issue with what seemed to be a native function that may have changed between versions, I played around with it for a bit and found that changing line 202 from:
> 
> `path = os.path.join([rootpath, folder])`
> 
> to
> 
> `path = os.path.join(rootpath, folder)`
> 
> fixed the issue for me. From what I can infer, the brackets passed the data in (perhaps as an array rather than a string) as the wrong data type. May want to see if it works for you.

**Yessssss**!  This is the fix, tested it on my broken copy in Windows.  You should have seen me I spent two days going through my entire library, the python script would break on Adding (so then i would copy paste the title into Radarr manually), run again, and it would break on the next movie.  Did this about 500+ time  :(  literally took the whole two days of my life

Now i gotta figure out the fastest way to add all the ones i skipped to the blacklist (might have to break the code again just to capture all the ids) lol

**Comment by RhinoRhys** [comment]
sorry its been a while, uploaded a new version that fixes this issue :)

**Comment by pcooney4** [comment]
Should the docker container automatically pick up this fix?  I'm still getting this error within docker.
