### ISSUE TITLE
Crash when movie is on Radarr's import-blacklist

### ISSUE THREAD

**Issue by hr1232** [RhinoRhys/radarr-collections#128]
**Error description:**
Whenever a movie is on Radarr's import-blacklist, this tool crashed instead of ignoring it.

**Steps to repoduce:**
- add 2 movies belonging to the same collection
- delete one of them and add them to the Radarr's blacklist (delete --> add list exclusion)
- run the tool
- as soon as it tries to add the missing movie for that incomplete collection, it will crash with this error:
```
Traceback (most recent call last):
  File "/app/rcm.py", line 496, in <module>
    else: tmdb_check(movie["tmdbId"])
  File "/app/rcm.py", line 254, in tmdb_check
    collection_check(col_id, tmdbId)
  File "/app/rcm.py", line 242, in collection_check
    for id_check in parts:  database_check(id_check, white_name, col_json, input_id)
  File "/app/rcm.py", line 165, in database_check
    elif excludeList and id_check in excludeList: log(words[u'text'][u'exclude'].format(*payload))
  File "/usr/local/lib/python3.9/configparser.py", line 1257, in __getitem__
    raise KeyError(key)
KeyError: 'exclude'
Total Movies Found: 0
```

**Current workaround:**
There are currently 3 ways to avoid the tool crashing in every run:
- Manually delete the entire collection in Radarr instead of just one unwanted movie
- Manually add the movie's TMDB-ID to a second, redundant blacklist in rcm.conf
- Remove the unwanted movie from Radarr's blacklist and live with it

**Expected behaviour:**
Tool should honor Radarr's exclusion list. Whenever a movie is in there, this tool should not try to add it. Blacklist setting in rcm.conf should be removed as it is redundant to Radarr's own blacklist.

**Comment by RhinoRhys** [comment]
Please download the newest words.conf file. Your older file is missing the "rejected: in radarr blocklist" message.
