### ISSUE TITLE
Add python2 shebang to script and chmod +x it so it can just be run

### ISSUE THREAD

**Issue by fryfrog** [RhinoRhys/radarr-collections#60]
May as well add `#!/usr/bin/env python2` as the first line and `chmod +x` it so it can just be run directly, why not? :)

https://stackoverflow.com/questions/6908143/should-i-put-shebang-in-python-scripts-and-what-form-should-it-take

**Comment by RhinoRhys** [comment]
It's already got the shebang in if you would like to run it that way. I wanted to make it as easy as possible to run so I've stuck with simply using the python command in the readme but feel free to run it directly if you want. Honestly I wouldn't even know what to do to make it work on Windows so I've avoided writing instructions for that and setting up scheduled running.

**Comment by fryfrog** [comment]
In that case, just `chmod +x` it and commit that.
