### ISSUE TITLE
Move configuration file name to `config.default.py` and add config.py to .gitignore

### ISSUE THREAD

**Issue by fryfrog** [RhinoRhys/radarr-collections#62]
If you change the configuration file name to `.default` and force people to rename it properly, you can make changes to the default w/o wiping their config file. You can also add the `config.py` to a `.gitignore` file and so people can have a git checkout of it *and* a modified config w/o having issues.

**Comment by si0972** [comment]
Ability to define the logs and output folders would be nice too.

**Comment by fryfrog** [comment]
Might as well let config be specified on command line, so it can live anywhere. Maybe even a few default search paths like `~/.config` and `/etc/somewhere`. :)

**Comment by RhinoRhys** [comment]
Config.py is already in .gitignore but it must be wrong because it doesn't seem to ignore it. A .default file is a good idea though. Sorry this is my first experience writing an app or using Git so I'm making it up as I go along :)

**Comment by fryfrog** [comment]
My *guess* is that because the file is committed to the repo, being in `.gitignore` doesn't matter. That is for untracked files, not tracked files. You might also add the `logs` and `output` and `*.pyc` to `.gitignore`.

**Comment by RhinoRhys** [comment]
It was because I created .gitignore after already committing the config.py initially, yeah. Changing to the .default filename has made the ignore work yay!
