### ISSUE TITLE
Not accepting port when baseurl is enabled. 

### ISSUE THREAD

**Issue by si0972** [RhinoRhys/radarr-collections#63]
I run a reverse proxy, but prefer to connect to the service internally, so i need to use 7878

**Comment by fryfrog** [comment]
Ah, *this* is what I saw! I enabled base url and it was obviously trying to connect to my reverse proxy. So I just "fixed" it by letting it do that. But it *should* have been able to connect to my actual instance.

**Comment by RhinoRhys** [comment]
The reverse proxy doesn't _need_ to be set even if you have one running.
Using "off" just makes the url `host:port` whereas putting anything else makes the url `host/base_url`. It's there because I have my reverse proxy set up to work locally too so I'm accessing mine via `mediaserver/film` on the local network rather than `192.168.1.250:7878`, If you can still access Radarr using the port locally, just leave it as "off" and it should be fine I think?

**Comment by fryfrog** [comment]
No, because most people set url base directly on their radarr too so that
domain.com/radarr and ip:port/radarr work the same.

**Comment by RhinoRhys** [comment]
Ooooh yeah, I get you now. Yeah I didn't think that through properly, I'll add a True/False switch rather than having it use "off" as the indicator.

**Comment by RhinoRhys** [comment]
Sorry could you post your traceback please. I'm not having any issues connecting regardless of it being `host/radarr/api`, `host:port/api` or  `host:port/radarr/api`.

**Comment by fryfrog** [comment]
```
0 ✓ fryfrog@apollo ~/git/radarr-collections $[master] python2 rcm.py -c
Welcome to Radarr Collection and People Manager by u/RhinoRhys

Traceback (most recent call last):
  File "rcm.py", line 275, in <module>
    data = api("Radarr")
  File "rcm.py", line 134, in api
    response = requests.get(url, params = key )
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 668, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 247, in resolve_redirects
    **adapter_kwargs
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='10.0.1.2', port=443): Max retries exceeded with url: /radarr/api/movie?apikey=602c5a0990754e1aa34816a8be5cab40 (Caused by SSLError(CertificateError("hostname '10.0.1.2' doesn't match either of 'apollo.fryfrog.com', 'fryfrog.com', 'www.fryfrog.com'",),))
```

**Comment by RhinoRhys** [comment]
Ah crap if it's going through 443 it won't like that it's only http://. Updated
