### ISSUE TITLE
Results vs Output mismatch

### ISSUE THREAD

**Issue by rustypasini** [RhinoRhys/radarr-collections#88]
rcm.py script reference config section called "results" (lines 54 & 55), however the section in rcm.conf is called "output" (line 32), which generates a KeyError.

```
if config[u'results'][u'path'] == "": config[u'results'][u'path'] = "./"
output_path = get_dir(config[u'results'][u'path'])

```

**Comment by RhinoRhys** [comment]
sorry I forgot to update the default config file duh!!!
