### ISSUE TITLE
Exclude movie from auto list import

### ISSUE THREAD

**Issue by oliroe** [RhinoRhys/radarr-collections#98]
Hi

Is there any way for this tool to use the same exceptions as the inbuilt exclusion list in Radarr. It's far more convenient to use one list of exclusions and doing it within the UI is easier than adding them to a config file.

Great tool by the way

**Comment by RhinoRhys** [comment]
I tried that but unfortunately Net Import exclusions are coded into the list import function, they don't apply to things added via the API and cannot be exported to be parsed. Running it in caching mode produces a text list with all the TMDB IDs in if that helps. I took my results file, removed the IDs for the movies I wanted, then spent a few minutes removing everything else except the remaining IDs so all that was left was a blacklist formatted comma separated list.
